package provider

import (
	_ "embed"
	"encoding/json"
	"strings"
)

// Ollama does not publish per-token rates through an API: models.dev's
// ollama-cloud entry carries model IDs and release dates but no cost fields,
// and api.ollama.com returns IDs only. The per-million-token USD rates live on
// https://ollama.com/pricing, so they are vendored here as a snapshot that
// scripts/fetch-ollama-pricing.sh regenerates.
//
// The snapshot keys models by the base name the pricing page uses
// (deepseek-v4-flash), which is also the prefix of every API ID that serves it
// (deepseek-v4-flash, deepseek-v4-flash:0731), so lookupPricing's exact-then-
// longest-prefix matching resolves dated and sized variants against it.
//
// Prices are for Ollama Cloud (api.ollama.com). A local daemon runs the same
// weights on your own hardware for free; CostFor keeps answering for the
// "ollama" provider with the models.dev snapshot, which has no ollama entry,
// so local models show no price.

//go:embed modeldata/ollama-cloud-pricing.json
var ollamaCloudPricingFS []byte

// ollamaCloudPricing is the parsed embedded snapshot.
type ollamaCloudPricing struct {
	Source    string                 `json:"source"`
	FetchedAt string                 `json:"fetched_at"`
	Models    map[string]PricingRate `json:"models"`
	Peak      map[string]PricingRate `json:"peak"`
}

// PricingRate is one model's per-million-token USD rates from the pricing
// page. Absent rates (the page renders "-") decode as nil.
type PricingRate struct {
	Input     *float64 `json:"input"`
	Output    *float64 `json:"output"`
	CacheRead *float64 `json:"cache_read"`
}

var ollamaCloudPricingParsed = parseOllamaCloudPricing()

func parseOllamaCloudPricing() ollamaCloudPricing {
	var p ollamaCloudPricing
	// The file is embedded and generated by fetch-ollama-pricing.sh, which
	// validates the shape; a decode failure would panic at init.
	if err := json.Unmarshal(ollamaCloudPricingFS, &p); err != nil {
		panic("provider: embedded ollama-cloud-pricing.json is invalid: " + err.Error())
	}
	return p
}

// OllamaCloudCost returns the per-million-token USD rates for an Ollama Cloud
// model, using the same base-name matching as the rest of the pricing lookup.
// ok is false when the model is not in the snapshot.
func OllamaCloudCost(modelName string) (PricingModel, bool) {
	rate, ok := ollamaCloudLookup(ollamaCloudPricingParsed.Models, modelName)
	if !ok {
		return PricingModel{}, false
	}
	return ollamaCloudModel(rate), true
}

// OllamaCloudPeakCost returns the peak-hour rates for an Ollama Cloud model.
// Peak pricing applies 12:00-18:00 UTC Monday to Friday and only covers the
// models the peak table lists; ok is false otherwise.
func OllamaCloudPeakCost(modelName string) (PricingModel, bool) {
	rate, ok := ollamaCloudLookup(ollamaCloudPricingParsed.Peak, modelName)
	if !ok {
		return PricingModel{}, false
	}
	return ollamaCloudModel(rate), true
}

// ollamaCloudLookup resolves a model name against a snapshot section with
// exact match first, then longest prefix, mirroring lookupPricing so a dated
// cloud ID (deepseek-v4-flash:0731) resolves against its base entry
// (deepseek-v4-flash).
func ollamaCloudLookup(rates map[string]PricingRate, modelName string) (PricingRate, bool) {
	if len(rates) == 0 {
		return PricingRate{}, false
	}
	lower := strings.ToLower(strings.TrimSpace(modelName))
	if lower == "" {
		return PricingRate{}, false
	}
	if r, ok := rates[lower]; ok {
		return r, true
	}
	best := ""
	for id := range rates {
		if strings.HasPrefix(lower, id) && len(id) > len(best) {
			best = id
		}
	}
	if best == "" {
		return PricingRate{}, false
	}
	return rates[best], true
}

// ollamaCloudModel converts a snapshot rate to the shared PricingModel. The
// page has no cache-write or context-tier rates.
func ollamaCloudModel(r PricingRate) PricingModel {
	pm := PricingModel{
		Input:  derefRate(r.Input),
		Output: derefRate(r.Output),
	}
	if r.CacheRead != nil {
		pm.CacheRead = *r.CacheRead
	}
	return pm
}

func derefRate(p *float64) float64 {
	if p == nil {
		return 0
	}
	return *p
}
